services:
  portfolio:
    build: .
    container_name: portfolio
    image: portfolio:latest
    restart: always
    network_mode: "host"
    environment:
      - S3_BUCKET=${S3_BUCKET}
      - S3_URL=${S3_URL}
      - OAUTH_ID=${OAUTH_ID}
      - AUTH_ORIGIN=${AUTH_ORIGIN}
      - AUTH_TRUST_HOST=${AUTH_TRUST_HOST}
      - MONGODB_URL=${MONGODB_URL}
      - MONGODB_NAME=${MONGODB_NAME}
      - OAUTH_SECRET=${OAUTH_SECRET}
      - NUXT_SECRET=${NUXT_SECRET}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - PORT=${PORT}
      - NODE_ENV=production
    healthcheck:
      test:
        ["CMD", "curl", "-f", "http://localhost:3000/api/system/healthcheck"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 10s
